steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args:
    - build
    - ./backend/
    - -t
    - gcr.io/$PROJECT_ID/istio-demo-backend:$SHORT_SHA

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args:
    - push
    - gcr.io/$PROJECT_ID/istio-demo-backend:$SHORT_SHA

- name: 'python'
  id: 'Generate Deployment Files'
  entrypoint: /bin/sh
  args:
    - -c
    - |
    - chown -R root:root ./
      pip install -r ./generator/requirements.txt
      python ./generator/generator.py \
        --mode backend \
        --version $BRANCH_NAME \
        --image gcr.io/$PROJECT_ID/istio-demo-backend:$SHORT_SHA

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy'
  entrypoint: /bin/sh
  args:
    - |
    - gcloud container clusters get-credentials ${_GKE_CLUSTER} --zone ${_GCP_ZONE}
      export CLOUDSDK_COMPUTE_REGION=${_GCP_REGION}
      export CLOUDSDK_COMPUTE_ZONE=${_GCP_ZONE}
      export CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}
      kubectl apply -f k8s/outputs/
  
substitutions:
  _GCP_REGION: us-central1
  _GCP_ZONE: us-central1-c
  _GKE_CLUSTER: demo-cluster